require("tommiranta/plugins-setup")
require("tommiranta/core.options")
require("tommiranta/core.keymaps")
require("tommiranta/core.colorscheme")
-- require("tommiranta/plugins.comment")
-- require("tommiranta/plugins.nvim-tree")
require("tommiranta/plugins.lualine")
require("tommiranta/plugins.telescope")
require("tommiranta/plugins.metals")
require("tommiranta/plugins.nvim-cmp")
require("tommiranta/plugins.lsp.mason")
require("tommiranta/plugins.lsp.lspsaga")
require("tommiranta/plugins.lsp.lspconfig")
require("tommiranta/plugins.lsp.null-ls")
require("tommiranta/plugins.autopairs")
require("tommiranta/plugins.treesitter")
